(let ((main-file (expand-file-name "e2e/emacs/change-state.org" base-dir))
      (temp-file (expand-file-name (concat "e2e/emacs/change-state-"
                                           (int-to-string org-newtab-ws-port)
                                           ".org") base-dir)))
  (setq make-backup-files nil)
  (find-file temp-file)
  (exec-when-file-isnt-locked main-file
                              (lambda ()
                                (insert-file-contents main-file)))
  (save-buffer)
  (org-mode)
  (goto-char (point-min))
  (search-forward "Sample todo item")
  (beginning-of-line)
  (org-todo "TODO")
  (sleep-for 5)
  (goto-char (point-min))
  (search-forward "Sample todo item")
  (beginning-of-line)
  (org-todo "NEXT")
  (forward-line 1)
  (org-todo "TODO"))
