(let ((main-file (expand-file-name "org/change.org" tmp-dir)))
  (find-file main-file)
  (org-mode)
  (goto-char (point-min))
  (search-forward "Sample tagged item")
  (beginning-of-line)
  (org-set-tags "NEWTAG"))
