name: 'Build extension'
on:
  workflow_call:

env:
  nodeVersion: 19
  pnpmVersion: 8
  retentionDays: 14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpmVersion }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodeVersion }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the extension for chrome
        run: pnpm run build

      - name: Build the extension for firefox
        run: pnpm run build --target=firefox-mv3

      - name: Package the extension for chrome
        run: pnpm run package

      - name: Add Chrome extension to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-mv3-prod.zip
          path: build/chrome-mv3-prod.zip
          retention-days: ${{ env.retentionDays }}

      - name: Package the extension for firefox
        run: pnpm run package --target=firefox-mv3

      - name: Add Firefox extension to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox-mv3-prod.zip
          path: build/firefox-mv3-prod.zip
          retention-days: ${{ env.retentionDays }}
