name: 'Create new GH release'
on:
  workflow_dispatch:

jobs:
  build-for-release:
    uses: ./.github/workflows/build.yml
    with:
      browser: all

  create-gh-release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-for-release]
    steps:
      - name: Get ver tag
        id: get_tag
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG_NUM="${TAG#v}"
          echo "Tag_num=$TAG_NUM" >> "$GITHUB_ENV"

      - name: Download Chrome artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-mv3-prod.zip

      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-mv3-prod.zip

      - name: Download Emacs artifact
        uses: actions/download-artifact@v4
        with:
          name: org-newtab-${{ env.Tag_num }}.tar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            firefox-mv3-prod.zip
            chrome-mv3-prod.zip
            org-newtab-${{ env.Tag_num }}.tar
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          generate_release_notes: true
          draft: true
