name: 'Submit to Firefox'
on:
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      browser: firefox

  submit:
    runs-on: ubuntu-latest
    needs: [call-build]
    steps:
      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-mv3-prod.zip

      - name: Browser Platform Publish for Firefox
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS_FIREFOX }}
          firefox-file: firefox-mv3-prod.zip
          verbose: true
