name: 'Submit to Web Store'
on:
  workflow_dispatch:

env:
  nodeVersion: 19
  pnpmVersion: 8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: ${{ env.pnpmVersion }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.nodeVersion }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the extension for chrome
        run: pnpm run build

      - name: Build the extension for firefox
        run: pnpm run build --target=firefox-mv3

      - name: Package the extension for chrome
        run: pnpm run package

      - name: Package the extension for firefox
        run: pnpm run package --target=firefox-mv3

      - name: Browser Platform Publish for Chrome
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS_CHROME }}
          artifact: build/chrome-mv3-prod.zip

      - name: Browser Platform Publish for Firefox
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS_FIREFOX }}
          artifact: build/firefox-mv3-prod.zip
