name: 'Submit to Chrome'
on:
  workflow_dispatch:

jobs:
  build-chrome:
    uses: ./.github/workflows/build.yml
    with:
      browser: chrome

  submit-chrome:
    runs-on: ubuntu-latest
    needs: [build-chrome]
    steps:
      - name: Download Chrome artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-mv3-prod.zip

      - name: Browser Platform Publish for Chrome
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS_CHROME }}
          chrome-file: chrome-mv3-prod.zip
          verbose: true
