name: 'Submit to Firefox'
on:
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Download Firefox artifact
        uses: actions/download-artifact@v4
        with:
          name: firefox-mv3-prod.zip

      - name: Browser Platform Publish for Firefox
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS_FIREFOX }}
          artifact: firefox-mv3-prod.zip
